grpc:
  port: 21000
server:
  port: 21001
springAppName: ServiceC
logging:
  level:
    ROOT: INFO
  file:
    path: logs
    name: ${logging.file.path}/servicec.log
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} %5p [${springAppName},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %5p [${springAppName},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n'
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1